### PR TITLE
Fix/deadlock on close

### PR DESCRIPTION
**Pull request by marcoconti83**
Remove deadlock on `CBCryptoBox close` caused by re-entrant `dyspatch_sync`.

As a comment, I would also argue that the current synchronization mechanism could be removed. Basically every call is wrapped in a `dyspatch_sync`, which is not better than documenting CBCryptoBox as not thread-safe and leaving the synchronization (if needed!) to the user.

### CODE REVIEW

**Comment by romanb** [comment]
I would advise against making the Objective-C API not thread-safe, as it is highly error-prone to put the burden on all client code to ensure all operations happen from the same thread or otherwise ensure appropriate memory barriers are in place. Uncontended synchronisation shouldn't have a significant overhead. It's easier to get it right within the relatively small bounds of the library API than in all client code that uses it. Just my 2 cents.

**Comment by marcoconti83** [comment]
@romanb I hear what you are saying. I am suggesting this just to follow the Cocoa practice.

Looking at the code I see two queues used for synchronization:

* One is a private global static synchronization queue used only to isolate calls to `cbox_file_open` to obtain a new instance of `CBoxRef`. I am not familiar with the internals but I assume this makes sense.

* One is a private instance property of `CBCryptoBox` used to synchronize access to the private internal `CBoxRef`. Hence this synchronization make sense only if we expect to use the specific `CBCryptoBox` instance from multiple threads. In most of the Cocoa framework, it is [assumed](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html) that instances of mutable classes are not thread safe and require synchronization on the user side. I would categorize `CBCryptoBox` as a mutable object so for consistency, and expecting users to be familiar with the concept, I would make it not thread safe. 

I don't have strong feelings on this though.

**Comment by marcoconti83** [comment]
Regardless of the discussion on thread safety (that we can maybe move to an Issue), what about merging this PR?

**Comment by romanb** [comment]
@marcoconti83 I'm leaving PRs for @kompozer to merge. I actually realise that it was not a good idea to integrate the Objective-C wrapper into my repository because I cannot actually maintain it. The only thing I can do in this repository is to release cross-compiled binaries. I would suggest that you move development of the Objective-C Wrapper into its own repository (e.g. `cryptobox-objective-c`) in either yours or @kompozer's account. You can then just fetch / integrate the binaries I release here into your build at your own pace. How does that sound? In any case, I will just merge the two PRs for now.

**Comment by kompozer** [comment]
@marcoconti83 Please check my pull request about this issue https://github.com/romanb/cryptobox-ios/pull/7 Part of it is also a bit cleaning up and removing the not needed NSError objects. If you agree, I would close this pull request and merge in mine.

**Comment by marcoconti83** [comment]
@romanb sounds good!
@kompozer  will do

**Comment by kompozer** [comment]
Closing this one, since its handled with https://github.com/romanb/cryptobox-ios/pull/7

**Comment by marcoconti83** [comment]
@roman, we will use https://github.com/ilyapuchka/cryptobox-ios

**Comment by romanb** [comment]
@marcoconti83 Great, thanks! I will remove the Objective-C parts from this repository then in the near future and will continue to release cross-compiled binaries here on every cryptobox release.

**Pull request closed without merging**
